server {
    listen 80;
    server_name _;

    root /var/www/my-site/pages;
    index main.html;

    location / {
        try_files $uri $uri/ /main.html;
    }

    location /styles/ {
        alias /var/www/my-site/styles/;
    }

    location /scripts/ {
        alias /var/www/my-site/scripts/;
    }

    location /assets/ {
        alias /var/www/my-site/assets/;
    }
}